### ISSUE TITLE
Non expanded children are build lazy

### ISSUE THREAD

**Issue by zellidev0** [Taskulu/sliver_expandable#2]
Hi,

I'm using the package for a expandable Tree structure, that's indefinitely nested.
It looks to me that the widget does not build the children widgets lazily.

Am I correct in this assumption?
And if so, is there a reason for that?

Wouldn't it be beneficial, if the widgets that are expanded would only be build, when they are expanded?

Thanks.

**Comment by Amir-P** [comment]
Hi! Thanks for pointing it out. Right now, not only the sliver will be built even if it's not expanded, in case of something like `SliverList`, the children gets built too based on the offset. I haven't found the time to do the optimizations and surely there's a lot to do. I will work on them but in the meantime feel free to contribute.

**Comment by Amir-P** [comment]
I believe #4 fixes this issue. Could you please give it a try and verify the fix? @zellidev0 
 
```
  sliver_expandable:
    git:
      url: https://github.com/Taskulu/sliver_expandable
      ref: feat/layout_sliver_only_when_expanded
```
